# Generated by Django 4.2 on 2023-04-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_email_alter_usuario_nome_and_more'),
        ('usuario', '0002_alter_usuario_password'),
    ]

    operations = [
    ]
