# Generated by Django 4.2 on 2023-04-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_merge_20230428_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'O email informado ja existe.'}, max_length=254, unique=True),
        ),
    ]
