# Generated by Django 4.2 on 2023-04-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('horario', models.TimeField(unique=True)),
                ('alarme', models.BooleanField(default=True)),
            ],
        ),
    ]
