# Generated by Django 4.1.7 on 2023-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='alarme',
            field=models.BooleanField(default=True),
        ),
    ]
