# Generated by Django 4.1.7 on 2023-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0002_alter_refeicao_alarme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='alarme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='horario',
            field=models.TimeField(unique=True),
        ),
    ]
