# Generated by Django 4.1.7 on 2023-04-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0004_alter_refeicao_alarme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='alarme',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
