# Generated by Django 4.2 on 2023-04-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0003_alter_refeicao_horario'),
        ('refeicao', '0006_alter_refeicao_alarme'),
    ]

    operations = [
    ]
